# The config file contains all parameters that can / have to be changed for the analyses

# Parameters for input and output data #########################################

samples:
    AFP2_O3_E_R_D07: "AFP2_O3_E_R_D07"

#   T1_S5_R_1_mil: "T1_S5_R_1_mil"
#   B002: 'B002'  # Samples names start with B only
#   B001: 'B001'

raw: "../data/sfb_aq_s_21_MT_total_RNA"
results: "sfb_aq_s_21_MT_total_RNA_results" # Folder for results. It will be created.
format: "fastq" # File format of the unzipped samples, i. e. "fasta" or "fastq".
reads: ["R1", "R2"]
# Performance parameters #######################################################

threads: 40 # Maximum number of threads used by single snakemake rule, the maximum is automatically set to cores.
maxmem: 500000 # Maximum memory used in mb. For assembly ensure sufficient memory.
io: 5 # Restriction on input/output operations.

# Cutadapt #####################################################################

adapter: "GATCGGAAGAGCA" # Illumina adapter sequence, first 13bp
##  ASSEMBLY
assembly: "SPADES" ## or "TRINITY"

# Databases ####################################################################

# Databases ####################################################################

#database_dir: "database_ncbi/" # Directory for NCBI databases

NCBI: "v5" # NCBI database version, will be saved in database_dir if not present
#taxdmp: "2020-10-01" # NCBI taxdump version, will be saved in database_dir if not present
sortmerna: "v4.2.0" # sortMeRNA database version
# JGI_database
jgi_config: "jgi_download.config"
jgi_organism_ids: "fungi_ids_list.txt"
#jgi_database_path: "jgi_database/aa_combined.fasta"

## KEGG Annotation
KO_list_file: "/mnt/biodiv/KEGG/kegg/genes/ko/ko_genes.list"
KEGG_pathways: "/mnt/biodiv/KEGG/kegg/pathway/pathway.list"
